# Generated by Django 3.2.3 on 2021-07-02 08:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nozzel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ntransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.FloatField()),
                ('type', models.CharField(choices=[('paytm', 'paytm'), ('googlepay', 'googlepay'), ('bank', 'bank'), ('phonepay', 'phonepay'), ('cash', 'cash')], max_length=20)),
                ('bankname', models.CharField(blank=True, max_length=20, null=True)),
                ('branchname', models.CharField(blank=True, max_length=20, null=True)),
                ('reference_id', models.CharField(blank=True, max_length=20, null=True)),
                ('totalpetrol', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, 'Value must be greater than 0')])),
                ('totaldiesel', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, 'Value must be greater than 0')])),
                ('totalpprice', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, 'Value must be greater than 0')])),
                ('totaldprice', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, 'Value must be greater than 0')])),
                ('petrolbefore', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, 'Value must be greater than 0')])),
                ('dieselbefore', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, 'Value must be greater than 0')])),
                ('petrolafter', models.FloatField(blank=True, null=True)),
                ('dieselafter', models.FloatField(blank=True, null=True)),
                ('lostpetrol', models.FloatField(blank=True, null=True)),
                ('lostdiesel', models.FloatField(blank=True, null=True)),
                ('lostpetrolprice', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, 'Value must be greater than 0')])),
                ('lostdieselprice', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, 'Value must be greater than 0')])),
                ('openingtime', models.TimeField()),
                ('closingtime', models.TimeField()),
                ('openinglitpetrol', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, 'Value must be greater than 0')])),
                ('closinglitpetrol', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, 'Value must be greater than 0')])),
                ('Openinglitdiesel', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, 'Value must be greater than 0')])),
                ('closinglitdiesel', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, 'Value must be greater than 0')])),
                ('creditorslipno', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, 'Value must be greater than 0')])),
                ('nozzelid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='nozzel.nozzel_master')),
            ],
        ),
    ]
