# Generated by Django 3.2.3 on 2021-07-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('n_transaction', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ntransaction',
            old_name='Openinglitdiesel',
            new_name='openinglitdiesel',
        ),
        migrations.AlterField(
            model_name='ntransaction',
            name='closingtime',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ntransaction',
            name='openingtime',
            field=models.FloatField(),
        ),
    ]
