# Generated by Django 3.2.3 on 2021-07-11 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('n_transaction', '0004_rename_creditorslipno_ntransaction_creditoramount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ntransaction',
            name='closingtime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ntransaction',
            name='openingtime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
