# Generated by Django 3.2.3 on 2021-06-30 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0006_alter_employee_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='employeepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.FloatField()),
                ('finalisesalary', models.FloatField()),
                ('type', models.CharField(choices=[('paytm', 'paytm'), ('googlepay', 'googlepay'), ('bank', 'bank'), ('phonepay', 'phonepay'), ('cash', 'cash')], max_length=20)),
                ('bankname', models.CharField(blank=True, max_length=20, null=True)),
                ('chequeno', models.FloatField(blank=True, null=True)),
                ('branchname', models.CharField(blank=True, max_length=20, null=True)),
                ('check_date', models.DateField(blank=True, null=True)),
                ('IFSC', models.IntegerField(blank=True, null=True)),
                ('reference_id', models.CharField(blank=True, max_length=20, null=True)),
                ('employeeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='employee.employee')),
            ],
        ),
    ]
