# Generated by Django 3.2.3 on 2021-07-15 09:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditor', '0004_auto_20210714_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditor_master',
            name='creationdate',
            field=models.DateField(default=datetime.datetime.utcnow),
        ),
    ]
