# Generated by Django 3.2.3 on 2021-07-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditor', '0005_alter_creditor_master_creationdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditor_master',
            name='homeno',
            field=models.CharField(max_length=10),
        ),
    ]
