# Generated by Django 3.2.5 on 2021-07-19 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='remark',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
