# Generated by Django 3.2.3 on 2021-06-30 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_payment', '0002_alter_c_payment_chequeno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c_payment',
            name='type',
            field=models.CharField(choices=[('paytm', 'paytm'), ('googlepay', 'googlepay'), ('bank', 'bank'), ('phonepay', 'phonepay'), ('cash', 'cash')], max_length=20),
        ),
    ]
