# Generated by Django 3.2.3 on 2021-07-15 09:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_payment', '0003_alter_c_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c_payment',
            name='date',
            field=models.DateField(default=datetime.datetime.utcnow),
        ),
    ]
