# Generated by Django 3.2.3 on 2021-07-15 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('c_payment', '0005_c_payment_slipno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='c_payment',
            name='slipno',
        ),
    ]
