# Generated by Django 3.2.3 on 2021-07-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_auto_20210714_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='vaccinate',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
