# Generated by Django 3.2.3 on 2021-06-27 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('creditor', '0003_auto_20210625_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('v_no', models.CharField(max_length=20)),
                ('driver_name', models.CharField(blank=True, max_length=25, null=True)),
                ('fuel_type', models.CharField(choices=[('petrol', 'petrol'), ('diesel', 'diesel')], max_length=10)),
                ('remarks', models.CharField(max_length=40)),
                ('creditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='creditor.creditor_master')),
            ],
        ),
    ]
