# Generated by Django 3.2.3 on 2021-07-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_alter_vehicle_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='remarks',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='v_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
