# Generated by Django 3.2.3 on 2021-07-02 09:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='calcmasters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ptank_open', models.FloatField()),
                ('ptank_close', models.FloatField()),
                ('dtank_open', models.FloatField()),
                ('dtank_close', models.FloatField(blank=True, null=True)),
                ('totalpetrol', models.FloatField(blank=True, null=True)),
                ('totaldiesel', models.FloatField(blank=True, null=True)),
                ('lostpetrol', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, 'Value must be greater than 0')])),
                ('lostdiesel', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, 'Value must be greater than 0')])),
            ],
        ),
    ]
