# Generated by Django 3.2.3 on 2021-07-11 03:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calcmasters',
            name='date',
            field=models.DateField(default=datetime.datetime.utcnow),
        ),
    ]
