# Generated by Django 3.2.3 on 2021-07-17 10:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0002_alter_calcmasters_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calcmasters',
            name='dtank_close',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='calcmasters',
            name='dtank_open',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='calcmasters',
            name='lostdiesel',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0, 'Value must be greater than 0')]),
        ),
        migrations.AlterField(
            model_name='calcmasters',
            name='lostpetrol',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0, 'Value must be greater than 0')]),
        ),
        migrations.AlterField(
            model_name='calcmasters',
            name='ptank_close',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='calcmasters',
            name='ptank_open',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='calcmasters',
            name='totaldiesel',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='calcmasters',
            name='totalpetrol',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
