# Generated by Django 3.2.3 on 2021-06-30 05:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='supplierdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('receipt_no', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Value must be greater than 0')])),
                ('petrolbefore', models.FloatField()),
                ('dieselbefore', models.FloatField()),
                ('time', models.TimeField()),
                ('petrolloss', models.FloatField(blank=True, null=True)),
                ('dieselloss', models.FloatField(blank=True, null=True)),
                ('transportation_in', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Value must be greater than 0')])),
            ],
        ),
    ]
