# Generated by Django 3.2.3 on 2021-06-29 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nozzel', '0001_initial'),
        ('c_transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c_transaction',
            name='nozzle_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c', to='nozzel.nozzel_master'),
        ),
    ]
