# Generated by Django 3.2.3 on 2021-06-29 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nozzel', '0001_initial'),
        ('c_transaction', '0002_alter_c_transaction_nozzle_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='c_transaction',
            name='nozzle_id',
        ),
        migrations.AddField(
            model_name='c_transaction',
            name='nozzel',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='nozzel', to='nozzel.nozzel_master'),
            preserve_default=False,
        ),
    ]
