# Generated by Django 3.2.3 on 2021-07-15 09:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_transaction', '0003_auto_20210629_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c_transaction',
            name='date',
            field=models.DateField(default=datetime.datetime.utcnow),
        ),
    ]
