# Generated by Django 3.2.3 on 2021-07-19 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_transaction', '0004_alter_c_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='c_transaction',
            name='dieselrates',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='c_transaction',
            name='petrolrates',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
