# Generated by Django 3.2.3 on 2021-07-19 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_transaction', '0005_auto_20210719_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='c_transaction',
            name='companyname',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='c_transaction',
            name='drivername',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
