# Generated by Django 3.2.3 on 2021-07-15 09:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tank', '0002_auto_20210625_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tank_master',
            name='date',
            field=models.DateField(default=datetime.datetime.utcnow),
        ),
    ]
